rm -f -r ./MeshSharp/bin/
rm -f -r ./MeshSharp/obj/
rm -f -r ./MeshSharp.Examples/bin/
rm -f -r ./MeshSharp.Examples/obj/
rm -f -r ./MeshSharp.FBX/bin/
rm -f -r ./MeshSharp.FBX/obj/
rm -f -r ./MeshSharp.GLTF/bin/
rm -f -r ./MeshSharp.GLTF/obj/
rm -f -r ./MeshSharp.OBJ/bin/
rm -f -r ./MeshSharp.OBJ/obj/
rm -f -r ./MeshSharp.PLY/bin/
rm -f -r ./MeshSharp.PLY/obj/
rm -f -r ./MeshSharp.PMX/bin/
rm -f -r ./MeshSharp.PMX/obj/
rm -f -r ./MeshSharp.STL/bin/
rm -f -r ./MeshSharp.STL/obj/
rm -f -r ./MeshSharp.Tests/bin/
rm -f -r ./MeshSharp.Tests/obj/
rm -f -r ./MeshSharp.Viewer/bin/
rm -f -r ./MeshSharp.Viewer/obj/

